# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10helloworld.proto\x12\nhelloworld\"C\n\x14\x43\x61\x64\x61strarCli_Request\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0b\n\x03\x63pf\x18\x02 \x01(\x03\x12\x10\n\x08\x65ndereco\x18\x03 \x01(\t\" \n\x12\x43\x61\x64\x61strarCli_Reply\x12\n\n\x02id\x18\x01 \x01(\x05\"\"\n\x13ObterCliCPF_Request\x12\x0b\n\x03\x63pf\x18\x01 \x01(\x03\" \n\x12ObterCliID_Request\x12\n\n\x02id\x18\x01 \x01(\x05\"I\n\x0eObterCli_Reply\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0b\n\x03\x63pf\x18\x02 \x01(\x03\x12\x10\n\x08\x65ndereco\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x05\x32\xf3\x01\n\x07Greeter\x12N\n\x08\x43\x61\x64\x61stra\x12 .helloworld.CadastrarCli_Request\x1a\x1e.helloworld.CadastrarCli_Reply\"\x00\x12L\n\x0bObtemPorCpf\x12\x1f.helloworld.ObterCliCPF_Request\x1a\x1a.helloworld.ObterCli_Reply\"\x00\x12J\n\nObtemPorID\x12\x1e.helloworld.ObterCliID_Request\x1a\x1a.helloworld.ObterCli_Reply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_CADASTRARCLI_REQUEST = _descriptor.Descriptor(
  name='CadastrarCli_Request',
  full_name='helloworld.CadastrarCli_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='helloworld.CadastrarCli_Request.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpf', full_name='helloworld.CadastrarCli_Request.cpf', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endereco', full_name='helloworld.CadastrarCli_Request.endereco', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=99,
)


_CADASTRARCLI_REPLY = _descriptor.Descriptor(
  name='CadastrarCli_Reply',
  full_name='helloworld.CadastrarCli_Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='helloworld.CadastrarCli_Reply.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=133,
)


_OBTERCLICPF_REQUEST = _descriptor.Descriptor(
  name='ObterCliCPF_Request',
  full_name='helloworld.ObterCliCPF_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpf', full_name='helloworld.ObterCliCPF_Request.cpf', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=169,
)


_OBTERCLIID_REQUEST = _descriptor.Descriptor(
  name='ObterCliID_Request',
  full_name='helloworld.ObterCliID_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='helloworld.ObterCliID_Request.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=203,
)


_OBTERCLI_REPLY = _descriptor.Descriptor(
  name='ObterCli_Reply',
  full_name='helloworld.ObterCli_Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='helloworld.ObterCli_Reply.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpf', full_name='helloworld.ObterCli_Reply.cpf', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endereco', full_name='helloworld.ObterCli_Reply.endereco', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='helloworld.ObterCli_Reply.id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=278,
)

DESCRIPTOR.message_types_by_name['CadastrarCli_Request'] = _CADASTRARCLI_REQUEST
DESCRIPTOR.message_types_by_name['CadastrarCli_Reply'] = _CADASTRARCLI_REPLY
DESCRIPTOR.message_types_by_name['ObterCliCPF_Request'] = _OBTERCLICPF_REQUEST
DESCRIPTOR.message_types_by_name['ObterCliID_Request'] = _OBTERCLIID_REQUEST
DESCRIPTOR.message_types_by_name['ObterCli_Reply'] = _OBTERCLI_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CadastrarCli_Request = _reflection.GeneratedProtocolMessageType('CadastrarCli_Request', (_message.Message,), {
  'DESCRIPTOR' : _CADASTRARCLI_REQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CadastrarCli_Request)
  })
_sym_db.RegisterMessage(CadastrarCli_Request)

CadastrarCli_Reply = _reflection.GeneratedProtocolMessageType('CadastrarCli_Reply', (_message.Message,), {
  'DESCRIPTOR' : _CADASTRARCLI_REPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CadastrarCli_Reply)
  })
_sym_db.RegisterMessage(CadastrarCli_Reply)

ObterCliCPF_Request = _reflection.GeneratedProtocolMessageType('ObterCliCPF_Request', (_message.Message,), {
  'DESCRIPTOR' : _OBTERCLICPF_REQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.ObterCliCPF_Request)
  })
_sym_db.RegisterMessage(ObterCliCPF_Request)

ObterCliID_Request = _reflection.GeneratedProtocolMessageType('ObterCliID_Request', (_message.Message,), {
  'DESCRIPTOR' : _OBTERCLIID_REQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.ObterCliID_Request)
  })
_sym_db.RegisterMessage(ObterCliID_Request)

ObterCli_Reply = _reflection.GeneratedProtocolMessageType('ObterCli_Reply', (_message.Message,), {
  'DESCRIPTOR' : _OBTERCLI_REPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.ObterCli_Reply)
  })
_sym_db.RegisterMessage(ObterCli_Reply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=281,
  serialized_end=524,
  methods=[
  _descriptor.MethodDescriptor(
    name='Cadastra',
    full_name='helloworld.Greeter.Cadastra',
    index=0,
    containing_service=None,
    input_type=_CADASTRARCLI_REQUEST,
    output_type=_CADASTRARCLI_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ObtemPorCpf',
    full_name='helloworld.Greeter.ObtemPorCpf',
    index=1,
    containing_service=None,
    input_type=_OBTERCLICPF_REQUEST,
    output_type=_OBTERCLI_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ObtemPorID',
    full_name='helloworld.Greeter.ObtemPorID',
    index=2,
    containing_service=None,
    input_type=_OBTERCLIID_REQUEST,
    output_type=_OBTERCLI_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
